version: '2'
services:
    netcup-dyndns:
        container_name: netcup-dyndns
        network_mode: "host"
        environment:
            SCHEDULE: "*/10 * * * *"
            DOMAIN: "example.com"
            MODE: "@ *"
            IPV4: "yes"
            IPV6: "yes"
            CUSTOMER_ID: ${CUSTOMER_ID}
            API_KEY: ${API_KEY}
            API_PASSWORD: ${API_PASSWORD}
            TZ: "Europe/Berlin"
        restart: unless-stopped
        image: ghcr.io/lightlike/netcup-dyndns:latest
